name: build-test

on:
  [push]

  # configuração para pull requests

  # pull_request:

  #   paths-ignore:

  #     - '**.md'

  # push:

  #   branches:

  #     - main

  #     - releases/*

  #   paths-ignore:

  #     - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - working-directory: ./Aula 4/ui-testing
        run: npm install
      - working-directory: ./Aula 4/ui-testing
        run: npm run test
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        working-directory: ./Aula 4/ui-testing
        run: npm install
        with:
          working-directory: ./Aula 4/ui-testing
          #build: npm run build
          start: npm start
          run: npm run cypress
